version: '3.8'
services:
  db:
    image: postgres:16-alpine # Use a specific version of the official Postgres image
    container_name: my_postgres_db # Optional: Give your container a specific name
    environment:
      PGDATA: /var/lib/postgresql/data # Persist data to a named volume
      PGDATABASE: ${PGDATABASE} # Name of the default database
      PGUSER: ${PGUSER} # Username for the database
      PGPASSWORD: ${PGPASSWORD} # Password for the database
    ports:
      - '5432:5432' # Map host port 5432 to container port 5432
    volumes:
      - ./db_data:/var/lib/postgresql/data # Persist data to a named volume
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    # restart: always # Ensure the container restarts if it stops
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres']
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  db_data: # Define the named volume for data persistence
