version: '3.8'
services:
  db:
    image: postgres:16-alpine # Use a specific version of the official Postgres image
    # host_name: ${DB_HOST}
    container_name: my_postgres_db # Optional: Give your container a specific name
    environment:
      PGDATA: /var/lib/postgresql/data # Persist data to a named volume
      PGDATABASE: ${DB_DATABASE} # Name of the default database
      PGUSER: ${DB_USER} # Username for the database
      PGPASSWORD: ${DB_PASSWORD} # Password for the database
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Password for the database
      POSTGRES_USER: ${DB_USER} # Username for the database
    ports:
      - '5432:${DB_PORT}' # Map host port 5432 to container port 5432
    volumes:
      - ./src/db/db_data:/var/lib/postgresql/data # Persist data to a named volume
      - ./src/db/create_db.sql:/docker-entrypoint-initdb.d/create_database.sql
    # restart: always # Ensure the container restarts if it stops
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres']
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  db_data: # Define the named volume for data persistence
